#+title: Doom Emacs Configuration
#+author: Josh Meek
#+property: header-args emacs-lisp :tangle config.el
#+startup: fold

* Table of Contents :toc:
- [[#about-this-config][About This Config]]
- [[#updating-configel][Updating config.el]]
- [[#config-disclaimer][Config Disclaimer]]
- [[#user-identity][User Identity]]
- [[#font-settings][Font Settings]]
- [[#doom-emacs-theme][Doom Emacs Theme]]
- [[#line-numbering][Line Numbering]]
- [[#org-mode-settings][Org Mode Settings]]
  - [[#org-directory][Org Directory]]
  - [[#word-wrap-in-org-files][Word Wrap in Org Files]]
  - [[#denote][Denote]]
- [[#window-and-frame-management][Window and Frame Management]]
  - [[#initial-frame-sizing][Initial Frame Sizing]]
  - [[#focus-new-window][Focus New Window]]
- [[#remove-quit-verification][Remove Quit Verification]]
- [[#splash-image][Splash Image]]
- [[#company-adjustments][Company Adjustments]]

* About This Config
This org file is a /literate/ config file for [[https://github.com/doomemacs/doomemacs][Doom Emacs]]. What that means is that this file itself is evaluated and used to write out the actual config.el file that is read when Doom Emacs starts up. The config.el file is no longer edited directly. This process is called /tangling/. This allows us to write out our documentation directly alongside the /actual code/ that will be evaluated by Doom Emacs, which is pretty neat!

* Updating config.el
After making changes to any source block in this file, it must then be tangled, writing out the new version of config.el.

To do this, put your cursor on the property line at the top of the file, and do ~C-c C-c~. This will refresh Doom Emacs. Then, run ~M-x org-babel-tangle~ (or, use the keybinding ~C-c C-v t~). After running this tangle command, the config.el file should be updated.

You shouldn't need to run ~doom sync~ after updating your config.el, just reload Doom Emacs for the changes to take effect.

* Config Disclaimer
The following is a disclaimer that will be added to the resulting config.el file as a warning.

#+begin_src emacs-lisp
;; STOP!! DO NOT EDIT THIS FILE DIRECTLY!!
;; ----------------------------------------
;; This file is generated from README.org, a literate source file.
;; You should make any changes there and then regenerate this file per the instructions found there.
#+end_src

* User Identity
This sets my name and email address, which some emacs tools may use.

#+begin_src emacs-lisp
(setq user-full-name "Josh Meek"
      user-mail-address "meek.josh@gmail.com")
#+end_src

* Font Settings
Doom Emacs exposes five variables for controlling fonts:
- ~doom-font~ - The primary font to use
- ~doom-variable-pitch-font~ - a non-monospace font (where applicable)
- ~doom-big-font~ - The font used in ~doom-big-font-mode~, a mode designed for presentations or streaming.
- ~doom-symbol-font~ - font used for symbols
- ~doom-serif-font~ - font used for the ~fixed-pitch-serif~ face

More info on doom fonts can be found at ~C-h v doom-font~.

My default font I like to use for Emacs is made by JetBrains, called JetBrainsMono. You can download it here:  https://www.jetbrains.com/lp/mono/

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrains Mono" :size 14))
#+end_src

On my Macbook, the font size of 14 is a bit small to read. I still want 14 to be my default size elsewhere, but for Mac OS, I bump the size up to 16 instead, still using JetBrainsMono as the font.

#+begin_src emacs-lisp
(cond (:system 'macos
               (setq doom-font (font-spec :family "JetBrains Mono" :size 16))))
#+end_src

* Doom Emacs Theme
~doom-theme~ is used to set a color theme that will be used upon startup. To browse the other available themes, you can use ~M-x load-theme~ to check them out.

#+begin_src emacs-lisp
(setq doom-theme 'doom-dracula)
#+end_src

* Line Numbering
I prefer line numbering in all my Emacs documents. This line enables the display of line numbers. If you want to disable it, change this to ~nil~. For relative line numbers, change this to ~relative~ instead.

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src

* Org Mode Settings
These settings all pertain to org mode, Emac's brilliant mode for notetaking, todo lists, and so much more. Org mode is kind of like Markdown on steroids.

** Org Directory
This simply sets the default org mode directory to a folder in your user home directory called ~org~.

#+begin_src emacs-lisp
(setq org-directory "~/org/")
#+end_src

** Word Wrap in Org Files
This setting turns on ~visual-line-mode~ for org files, which wraps text to a new line if it does not visually fit based on your current window size.

#+begin_src emacs-lisp
(add-hook! org-mode :append
           #'visual-line-mode)
#+end_src

** Denote
[[https://github.com/protesilaos/denote][Denote]] is a tool for creating and managing notes and files that works amazingly with org mode. I use it to implement a [[https://zettelkasten.de/overview/][Zettelkasten]] (sorta) system for tracking and maintaining my notes into a kind of mind map, with interconnected links between files.

At the core, Denote will create a file for you with a very specific naming scheme: ~DATE==SIGNATURE--TITLE__KEYWORDS.EXTENSION~. This works great because you can very easily use dired or any other search mechanism to narrow files down based on name and keyword, and they are all sorted by date created.

Denote also has built-in tools for creating links between files, managing keywords and updating your file names, displaying backlinks, creating dynamic blocks inside files that display all other files with a matching regex, and so much more. Check out the [[https://protesilaos.com/emacs/denote][full manual]] for all of Denote's powerful features, as I am just beginning to scratch the surface here.

*** Directory
This sets the default denote directory. Note that this is the same as my org mode default directory as well.

#+begin_src emacs-lisp
(require 'denote)
(setq denote-directory (expand-file-name "~/org/"))
#+end_src

*** Keywords
This is a starting list of keywords that denote will suggest. You don't need to stress too much about these, as you can create your own on the fly and denote will then 'know' the keywords you've used in any of your files as well.

#+begin_src emacs-lisp
(setq denote-known-keywords '("emacs" "programming" "managing" "learning"))
#+end_src

*** Dates
Use org mode's date picking interface when needed.

#+begin_src emacs-lisp
(setq denote-date-prompt-use-org-read-date t)
#+end_src

*** Backlinks
This tells denote to show a few lines of context from the file when display backlinks, instead of just showing the file name.

#+begin_src emacs-lisp
(setq denote-backlinks-show-context t)
#+end_src

*** Fontification
This setting does not currently work in Doom Emacs because Doom uses diredfl, and these fontification settings do not work when diredfl is enabled. However, I'm leaving them here as reference in case that ever changes.

#+begin_src emacs-lisp
(setq denote-dired-directories-include-subdirectories t)
(setq denote-dired-directories
      (list denote-directory
            (expand-file-name "~/org/")))
(add-hook 'dired-mode-hook #'denote-dired-mode-in-directories)
#+end_src

*** Key Mapping
This section defines some custom key mappings for denote that attempt to fit into the same format and flow as the other Doom Emacs keymappings. Mainly, this means that the all start with ~SPACE d~ for denote, and then try to choose sensible letters that are easy to remember.

Not every denote function is present here, just the ones I use most often in my day-to-day workflow.

#+begin_src emacs-lisp
(map! :leader
      (:prefix-map ("d" . "denote")
                :desc "new denote note" "d" #'denote
                :desc "link to existing note, or create a new note" "l" #'denote-link-or-create
                (:prefix ("b" . "backlinks")
                         :desc "show backlinks to the current note" "b" #'denote-backlinks
                         :desc "next backlink" "j" #'denote-backlinks-mode-next
                         :desc "previous backlink" "k" #'denote-backlinks-mode-previous)
                (:prefix ("s" . "stats")
                         :desc "count notes" "c" #'denote-explore-count-notes
                         :desc "count keywords" "k" #'denote-explore-count-keywords
                         :desc "keywords barchart" "b" #'denote-explore-keywords-barchart
                         :desc "extensions barchart" "e" #'denote-explore-extensions-barchart)
                (:prefix ("u" . "Utilities")
                         :desc "insert dynamic links block" "l" #'denote-org-extras-dblock-insert-links
                         :desc "update dynamic links block" "u" #'org-dblock-update)
                (:prefix ("r" . "random walks")
                         :desc "random note" "r" #'denote-explore-random-note
                         :desc "random link" "l" #'denote-explore-random-link
                         :desc "random keyword" "k" #'denote-explore-random-keyword)
                (:prefix ("j" . "janitor")
                         :desc "duplicate notes" "d" #'denote-explore-identify-duplicate-notes
                         :desc "zero keywords" "z" #'denote-explore-zero-keywords
                         :desc "single keywords" "i" #'denote-explore-single-keywords
                         :desc "sort keywords" "s" #'denote-explore-sort-keywords
                         :desc "rename keyword" "r" #'denote-explore-rename-keyword)))
#+end_src

*** Denote Explore
Denote Explore is an additional package that helps to visualize your denote notes and provides some helpful utilities for managing your notes, such as 'random walks' and some janitorial services that seek out duplicate notes, single keyword files, and more.

These settings just do some generic setup for denote explore, mainly specifying where the graph images should be created.

#+begin_src emacs-lisp
(use-package! denote-explore
  :custom
  ;; Location of graph files
  (denote-explore-network-directory "~/org/graphs/")
  (denote-explore-network-filename "denote-network")
  ;; Output format
  (denote-explore-network-format 'graphviz)
  (denote-explore-network-graphviz-filetype "svg")
  ;; Exlude keywords or regex
  (denote-explore-network-keywords-ignore '("bib")))
#+end_src

* Window and Frame Management
These settings pertain to either the Emacs "window" itself (the frame) or to split windows inside of Emacs.

** Initial Frame Sizing
This sets the initial size of the Doom Emacs window to be proportional to the screen displaying it. It should take up 70% of the window, and be centered.

This was taken from: https://www.reddit.com/r/emacs/comments/9c0a4d/tip_setting_initial_frame_size_and_position/

#+begin_src emacs-lisp
(defun my/set-initial-frame ()
  (let* ((base-factor 0.70)
         (a-width (* (display-pixel-width) base-factor))
         (a-height (* (display-pixel-height) base-factor))
         (a-left (truncate (/ (- (display-pixel-width) a-width) 2)))
         (a-top (truncate (/ (- (display-pixel-height) a-height) 2))))
    (set-frame-position (selected-frame) a-left a-top)
    (set-frame-size (selected-frame) (truncate a-width)  (truncate a-height) t)))
(setq frame-resize-pixelwise t)
(my/set-initial-frame)
#+end_src

** Focus New Window
After splitting a window (either vertically or horizontally), this makes it so that the new window immediately has focus, instead of requiring you to switch to it.

#+begin_src emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src

* Remove Quit Verification
By default, Doom Emacs asks if you really want to quit when you try to quit. This is annoying. This stops that from happening.

#+begin_src emacs-lisp
(setq confirm-kill-emacs nil)
#+end_src

* Splash Image
The splash image is displayed when you first open Doom Emacs, and for a bit of fun we can change it to something a smidge flashier. I came across these images and the idea to modify the splash screen here: https://gitlab.com/zzamboni/dot-doom/-/tree/master/splash

The following code will randomly choose a splash image from amongst the ones listed and display it on the start page. Any new splash images should be placed in ~.doom.d/splash~ and then added to this list.

#+begin_src emacs-lisp
(let ((alternatives '(;;"doom-emacs-color.png"
                      ;;"doom-emacs-color2.svg"
                      ;;"doom-emacs-bw-light.svg"
                      "doom-emacs-flugo-slant_out_purple.png"
                      ;;"doom-emacs-flugo-slant_out_bw.png"
                      )))
  (setq fancy-splash-image
        (concat doom-user-dir "splash/"
                (nth (random (length alternatives)) alternatives))))
#+end_src

* Company Adjustments
Company is the autocompletion tool that Doom Emacs uses, and it can get quite annoying when it tries to autocomplete in a text note. The following code is all trying to disable company in org mode files, and /something/ is working to do that, but I'm not sure exactly which piece. Further investigation will need to be done to determine what can be removed.

#+begin_src emacs-lisp
(after! company
  (set-company-backend! 'org-mode nil))

(setq company-global-modes '(not org-mode))

(after! company
    ;;; Prevent suggestions from being triggered automatically. In particular,
  ;;; this makes it so that:
  ;;; - TAB will always complete the current selection.
  ;;; - RET will only complete the current selection if the user has explicitly
  ;;;   interacted with Company.
  ;;; - SPC will never complete the current selection.
  ;;;
  ;;; Based on:
  ;;; - https://github.com/company-mode/company-mode/issues/530#issuecomment-226566961
  ;;; - https://emacs.stackexchange.com/a/13290/12534
  ;;; - http://stackoverflow.com/a/22863701/3538165
  ;;;
  ;;; See also:
  ;;; - https://emacs.stackexchange.com/a/24800/12534
  ;;; - https://emacs.stackexchange.com/q/27459/12534

  ;; <return> is for windowed Emacs; RET is for terminal Emacs
  (dolist (key '("<return>" "RET"))
    ;; Here we are using an advanced feature of define-key that lets
    ;; us pass an "extended menu item" instead of an interactive
    ;; function. Doing this allows RET to regain its usual
    ;; functionality when the user has not explicitly interacted with
    ;; Company.
    (define-key company-active-map (kbd key)
      `(menu-item nil company-complete
                  :filter ,(lambda (cmd)
                             (when (company-explicit-action-p)
                              cmd)))))
  ;; (define-key company-active-map (kbd "TAB") #'company-complete-selection)
  (map! :map company-active-map "TAB" #'company-complete-selection)
  (map! :map company-active-map "<tab>" #'company-complete-selection)
  (define-key company-active-map (kbd "SPC") nil)

  ;; Company appears to override the above keymap based on company-auto-complete-chars.
  ;; Turning it off ensures we have full control.
  (setq company-auto-commit-chars nil) ;; this appears to now be obsolete, replaced with the below
  (setq company-insertion-triggers nil)
  )
#+end_src
